version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.2
    - 2.18.3
    - 2.18.4
    - 2.18.5
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: phpspec/prophecy
    versions:
    - 1.12.2
  - dependency-name: predis/predis
    versions:
    - 1.1.6
