<?php

declare(strict_types=1);

namespace UniqueIdentityManager\Tests;

use League\Event\Emitter;
use League\Event\EmitterInterface;
use PHPUnit\Framework\TestCase as BaseTestCase;
use UniqueIdentityManager\Events\CustomerNewDeviceEvent;
use UniqueIdentityManager\Events\NewDeviceIdentityKeyEvent;
use UniqueIdentityManager\Events\UpdateCustomerIdentityKeyEvent;

class TestCase extends BaseTestCase
{
    /**
     * @var EmitterInterface
     */
    protected $emitter;

    /**
     * @var FakeListener
     */
    protected $listener;

    protected function setUp(): void
    {
        $this->emitter = new Emitter();
        $this->listener = new FakeListener();

        $this->emitter->addListener(
            CustomerNewDeviceEvent::EVENT_NAME,
            $this->listener
        );

        $this->emitter->addListener(
            NewDeviceIdentityKeyEvent::EVENT_NAME,
            $this->listener
        );

        $this->emitter->addListener(
            UpdateCustomerIdentityKeyEvent::EVENT_NAME,
            $this->listener
        );

        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
