name: CI

on: [push]

jobs:
  build:
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install composer dependencies
      run: composer install --prefer-dist

    - name: Run Lint & Tests
      run: composer run test
